import { expect, test } from '@playwright/test'

test('keeps heading # selectable, copyable, editable and deletable',async({page},info)=>{
 await page.goto('/e2e/rich-heading-fixture.html')
 const body=page.getByRole('textbox',{name:'文档正文'})
 await body.locator('p').first().click({position:{x:8,y:8}});await page.keyboard.press('Home');await page.keyboard.press('Shift+End')
 await expect.poll(()=>page.evaluate(()=>window.getSelection()?.toString())).toBe('上方正文')
 await page.keyboard.press('Backspace')
 await page.keyboard.type('#')
 await expect(page.locator('h1[data-rich-heading]').first()).toHaveText('#')
 await page.keyboard.type('## ');await page.keyboard.insertText('章节')
 const title=page.locator('h3[data-rich-heading]')
 await expect(title).toHaveText('### 章节')
 await page.keyboard.press('Home');await page.keyboard.press('Shift+End')
 await expect.poll(()=>page.evaluate(()=>window.getSelection()?.toString())).toBe('### 章节')
 await page.keyboard.insertText('## 新标题')
 const second=page.locator('h2[data-rich-heading]')
 await expect(second).toHaveText('## 新标题')
 await second.click({position:{x:8,y:8}});await page.keyboard.press('Home');await expect.poll(()=>page.evaluate(()=>window.getSelection()?.anchorOffset)).toBe(0)
 await page.keyboard.press('Delete');await expect(page.locator('h1[data-rich-heading]').first()).toHaveText('# 新标题')
 await page.keyboard.press('Delete');await expect(page.locator('.rich-document__content > p').filter({hasText:'新标题'})).toBeVisible()
 await page.screenshot({path:info.outputPath('heading-markers.png')})
})

test('Enter at the leading edge keeps an existing heading intact',async({page})=>{
 await page.goto('/e2e/rich-heading-fixture.html')
 const heading=page.locator('h4[data-rich-heading]')
 await heading.click();await page.keyboard.press('Home');await page.keyboard.press('Enter')
 await expect(heading).toHaveText('#### Self-Attention')
 await expect(page.locator('.rich-document__content > p').filter({hasText:'Self'})).toHaveCount(0)
})
test('uses the shortcut field for recording and opens a directory picker',async({page},info)=>{
 await page.goto('/');await page.getByRole('button',{name:'打开设置',exact:true}).click()
 await page.getByRole('tab',{name:'系统',exact:true}).click()
 const appearance=async(name:string)=>page.getByRole('button',{name,exact:true}).evaluate(element=>{const style=getComputedStyle(element);return {font:style.fontSize,height:style.height,border:style.borderColor,background:style.backgroundColor}})
 expect(await appearance('下次关闭时会询问')).toEqual(await appearance('检查更新'))
 await page.screenshot({path:info.outputPath('settings-system.png')})
 await page.getByRole('tab',{name:'按键',exact:true}).click()
 await expect(page.getByRole('button',{name:'录制便笺快捷键'})).toHaveCount(0)
 const shortcut=page.getByRole('textbox',{name:'便笺快捷键'})
 await shortcut.click();await expect(shortcut).toHaveValue('请按下按键…')
 await page.keyboard.press('Control+Alt+n');await expect(shortcut).toHaveValue('Ctrl+Alt+N')
 await shortcut.click();await page.keyboard.press('Escape');await expect(shortcut).toHaveValue('Ctrl+Alt+N')
 await page.getByRole('tab',{name:'存储',exact:true}).click()
 await page.getByRole('button',{name:'选择数据目录'}).click()
 await expect(page.getByRole('textbox',{name:'迁移目标文件夹'})).toHaveValue('E2E selected storage')
 await page.screenshot({path:info.outputPath('storage-picker.png')})
})
