import {test,expect} from '@playwright/test'

test('heading prefix follows focus and format painter copies its level',async({page},info)=>{
 await page.goto('/e2e/rich-heading-fixture.html?pane=document')
 const body=page.getByRole('textbox',{name:'文档正文'}),heading=body.locator('h4')
 await expect(heading.locator('.rich-document__source-prefix')).toHaveClass(/is-hidden/)
 await heading.click({position:{x:90,y:8}})
 await expect(heading.locator('.rich-document__source-prefix')).not.toHaveClass(/is-hidden/)
 await page.keyboard.press('Home');await page.keyboard.press('Shift+End')
 await page.getByRole('button',{name:'格式刷',exact:true}).click()
 await body.locator('p').last().click({position:{x:8,y:8}});await page.keyboard.press('Home');await page.keyboard.press('Shift+End')
 await expect(body.locator('h4')).toHaveCount(2)
 await expect(body.locator('h4').last()).toContainText('下方正文')
 await body.locator('p').first().click({position:{x:8,y:8}})
 await expect(body.locator('h4 .is-hidden')).toHaveCount(2)
 await page.screenshot({path:info.outputPath('heading-painter.png')})
})

test('rich gutter shows line number before plus and inserts before the hovered block',async({page},info)=>{
 await page.goto('/e2e/rich-heading-fixture.html?pane=document')
 const body=page.getByRole('textbox',{name:'文档正文'})
 await body.locator('p').last().hover()
 const controls=page.locator('.rich-document__block-controls')
 await expect(controls).toHaveClass(/is-visible/)
 await expect(controls.locator('span')).toHaveText('3')
 const number=await controls.locator('span').boundingBox(),plus=await controls.locator('button').boundingBox()
 expect(number!.x+number!.width).toBeLessThan(plus!.x)
 await controls.getByRole('button',{name:'添加内容块'}).click()
 const menu=page.getByRole('menu',{name:'插入内容'})
 await expect(menu.getByRole('menuitem',{name:'超链接',exact:true})).toBeVisible()
 await expect(menu.getByRole('menuitem',{name:'正文',exact:true})).toHaveCount(0)
 await expect(menu.getByRole('menuitem',{name:'标题 2',exact:true})).toHaveCount(0)
 await menu.getByRole('menuitem',{name:'分隔线',exact:true}).click()
 await expect(body.locator('hr')).toHaveCount(1)
 await expect(body.locator('p').last()).toHaveText('下方正文')
 await page.screenshot({path:info.outputPath('rich-gutter.png')})
})

test('markdown shows hovered line number beside its insertion menu',async({page},info)=>{
 await page.goto('/e2e/rich-heading-fixture.html?pane=markdown')
 await page.locator('.cm-line').last().hover()
 const number=page.locator('.markdown-line-number')
 await expect(number).toHaveClass(/is-visible/);await expect(number).toHaveText('3')
 await page.getByRole('button',{name:'添加内容块'}).click()
 await expect(page.getByRole('menu',{name:'Markdown 快捷插入'})).toBeVisible()
 await page.screenshot({path:info.outputPath('markdown-gutter.png')})
})

test('centers minimize glyph and unifies ordinary settings names',async({page},info)=>{
 await page.goto('/')
 await expect(page.getByRole('button',{name:'最小化窗口'}).locator('path')).toHaveAttribute('d','M6 12h12')
 await page.getByRole('button',{name:'打开设置',exact:true}).click()
 const typography=async(selector:string)=>page.locator(selector).first().evaluate(el=>{const s=getComputedStyle(el);return {size:s.fontSize,weight:s.fontWeight}})
 const ordinary=await typography('#settings-section-appearance > label')
 expect(await typography('#settings-section-appearance .settings-view__check strong')).toEqual(ordinary)
 await page.getByRole('tab',{name:'系统',exact:true}).click()
 expect(await typography('#settings-section-system .settings-view__check > span')).toEqual(ordinary)
 expect(await typography('#settings-section-system .settings-view__check strong')).toEqual(ordinary)
 await page.screenshot({path:info.outputPath('settings-type.png')})
})
