import {test,expect} from '@playwright/test'
test('records search binding, responds to it, and submits the sidebar query',async({page},info)=>{
 await page.goto('/')
 await page.getByRole('button',{name:'打开设置',exact:true}).click()
 await page.getByRole('tab',{name:'按键',exact:true}).click()
 const binding=page.getByRole('textbox',{name:'搜索快捷键'})
 await binding.click();await expect(binding).toHaveValue('请按下按键…')
 await page.keyboard.press('Control+k');await expect(binding).toHaveValue('Ctrl+K')
 await page.getByRole('tab',{name:'AI',exact:true}).click()
 const key=page.locator('.settings-view__key-control'),model=page.getByRole('combobox',{name:'总结模型'})
 expect((await key.boundingBox())?.width).toBeCloseTo((await model.boundingBox())?.width??0,0)
 await page.screenshot({path:info.outputPath('settings-ai.png')})
 await page.getByRole('button',{name:'完成',exact:true}).click()
 await page.keyboard.press('Control+k');await expect(page.getByRole('dialog',{name:'搜索资料库'})).toBeVisible()
 await page.keyboard.press('Escape')
 const sidebar=page.getByRole('searchbox',{name:'搜索笔记'})
 await sidebar.fill('身份');await sidebar.press('Enter')
 const results=page.getByLabel('资料库搜索结果')
 await expect(page.getByRole('dialog',{name:'搜索资料库'})).toHaveCount(0)
 await expect(results.locator('mark')).toHaveText('身份')
 await expect(results).toContainText('身份验证入口。')
 await page.screenshot({path:info.outputPath('search-highlight.png')})
})
test('shows a block number on hover and paints selected text',async({page},info)=>{
 await page.goto('/e2e/rich-heading-fixture.html?pane=document')
 const body=page.getByRole('textbox',{name:'文档正文'})
 const block=body.locator('[data-block-number]').first()
 await block.hover();await expect(page.locator('.rich-document__block-controls')).toHaveClass(/is-visible/)
 await expect(page.locator('.rich-document__block-number')).toHaveText('1')
 await page.getByRole('button',{name:'格式刷',exact:true}).hover();await expect(page.locator('.rich-document__block-controls')).not.toHaveClass(/is-visible/)
 await body.click();await page.keyboard.press('Control+Home');await page.keyboard.press('Home');await page.keyboard.press('Shift+End')
 await page.getByRole('button',{name:'粗体',exact:true}).click()
 await page.getByRole('button',{name:'格式刷',exact:true}).click();await expect(page.getByRole('button',{name:'格式刷',exact:true})).toHaveAttribute('aria-pressed','true')
 await body.locator('p').last().click({position:{x:8,y:8}});await page.keyboard.press('Home');await page.keyboard.press('Shift+End')
 await expect.poll(()=>page.evaluate(()=>window.getSelection()?.toString())).toBe('下方正文')
 await expect(page.getByRole('button',{name:'格式刷',exact:true})).toHaveAttribute('aria-pressed','false')
 await expect(body.locator('p').last().locator('strong')).toBeVisible()
 await page.screenshot({path:info.outputPath('block-painter.png')})
})

test('counts and numbers image and table blocks once',async({page},info)=>{
 await page.goto('/e2e/rich-heading-fixture.html?pane=document&blocks=1')
 const body=page.getByRole('textbox',{name:'文档正文'})
 await expect(page.getByLabel('笔记状态栏')).toContainText('6 行')
 await expect(body.locator('[data-block-number]')).toHaveCount(6)
 for(const number of ['4','5']) {
  await body.locator(`[data-block-number="${number}"]`).hover()
  await expect(page.locator('.rich-document__block-number')).toHaveText(number)
  await expect(page.locator('.rich-document__block-controls')).toHaveClass(/is-visible/)
 }
 await page.screenshot({path:info.outputPath('image-table-blocks.png')})
})
