import { expect, test } from '@playwright/test'

test('aligns settings controls and sizes fields for their contents', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 1180, height: 760 })
  await page.goto('/')
  await page.getByRole('button', { name: '打开设置', exact: true }).click()
  const theme = page.getByRole('combobox', { name: '主题' })
  const font = page.getByRole('combobox', { name: '正文字体' })
  const code = page.getByRole('combobox', { name: '代码字体' })
  const size = page.getByRole('spinbutton', { name: '界面字号' })
  await expect(theme).toBeVisible()
  const boxes = await Promise.all([theme, font, code].map((control) => control.boundingBox()))
  expect(Math.abs(boxes[0]!.x - boxes[1]!.x)).toBeLessThan(1)
  expect(Math.abs((await size.boundingBox())!.x + (await size.boundingBox())!.width - boxes[1]!.x - boxes[1]!.width)).toBeLessThan(1)
  expect(Math.abs(boxes[1]!.x - boxes[2]!.x)).toBeLessThan(1)
  expect((await size.boundingBox())!.width).toBeLessThan(120)
  await expect(page.getByRole('button', { name: '完成', exact: true })).toBeInViewport()
  await page.screenshot({ path: testInfo.outputPath('settings.png') })
  for (const name of ['系统', '按键', '存储', 'AI']) {
    await page.getByRole('tab', { name, exact: true }).click()
    await expect(page.getByRole('tabpanel', { name, exact: true })).toBeVisible()
    if (name === '系统') {
      const startup = (await page.getByRole('checkbox', { name: '开机启动' }).boundingBox())!
      const tray = (await page.getByRole('checkbox', { name: '关闭主窗口时隐藏到托盘' }).boundingBox())!
      expect(Math.abs(startup.x - tray.x)).toBeLessThan(1)
    }
    await page.screenshot({ path: testInfo.outputPath('settings-' + name + '.png') })
  }
  await page.getByRole('tab', { name: '常规' }).click()
  await theme.selectOption('night')
  await expect(theme).toHaveValue('night')
  await page.screenshot({ path: testInfo.outputPath('settings-night.png') })
})

test('centers a complete poem and uses a continuous divider at desktop widths', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('treeitem', { name: '项目', exact: true }).click()
  for (const width of [800, 1180]) {
    await page.setViewportSize({ width, height: 760 })
    const lyric = page.getByTestId('daily-lyric')
    await expect(lyric).toBeVisible()
    await expect.poll(() => lyric.evaluate((element) => {
      const text = element.querySelector('.daily-lyric__text')!
      const cite = element.querySelector('cite')!
      const a = text.getBoundingClientRect(), b = cite.getBoundingClientRect()
      return Math.abs((a.left + b.right) / 2 - window.innerWidth / 2)
    })).toBeLessThan(2)
    expect(await lyric.evaluate((element) => Array.from(element.children).every((child) => child.scrollWidth <= child.clientWidth))).toBe(true)
  }
  const divider = page.getByRole('separator', { name: '调整文件夹栏宽度' })
  const bounds = (await divider.boundingBox())!
  expect(bounds.width).toBe(1)
  const before = Number(await divider.getAttribute('aria-valuenow'))
  await page.mouse.move(bounds.x + 3, bounds.y + 100)
  await page.mouse.down()
  await page.mouse.move(bounds.x + 43, bounds.y + 100)
  await page.mouse.up()
  await expect.poll(async () => Number(await divider.getAttribute('aria-valuenow'))).toBeGreaterThan(before + 30)
  await page.setViewportSize({ width: 800, height: 760 })
  await page.getByRole('button', { name: '打开设置', exact: true }).click()
  await page.getByRole('spinbutton', { name: '界面字号' }).fill('28')
  await page.getByRole('spinbutton', { name: '界面字号' }).blur()
  await page.getByRole('button', { name: '完成', exact: true }).click()
  const lyric = page.getByTestId('daily-lyric')
  await expect.poll(() => lyric.evaluate((element) => Array.from(element.children).every((child) => child.scrollWidth <= child.clientWidth))).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('workspace.png') })
})

test('closes a temporary preview after saving and exposes only app context menus', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('treeitem', { name: '临时便笺', exact: true }).click()
  const capture = page.locator('.temporary-inbox__capture').filter({ hasText: '发布前检查' })
  const appearance = async () => capture.evaluate((element) => ({ background: getComputedStyle(element).backgroundColor, border: getComputedStyle(element).borderColor, row: getComputedStyle(element.closest('li')!).backgroundColor }))
  const beforeHover = await appearance()
  await capture.hover()
  expect(await appearance()).toEqual(beforeHover)
  await capture.click()
  const body = page.getByRole('textbox', { name: 'Markdown source' })
  await expect(body).toBeVisible()
  await expect(page.getByTestId('ai-summary-widget')).toHaveCount(0)
  await expect(page.locator('.temporary-inbox__list .is-active')).toHaveCount(1)
  await body.fill('保存后关闭')
  await page.locator('.temporary-inbox__capture').filter({ hasText: '保存后关闭' }).click()
  await expect(body).toHaveCount(0)
  await page.locator('.temporary-inbox__capture').filter({ hasText: '保存后关闭' }).click()
  await expect(body).toHaveText('保存后关闭')
  const prevented = await page.locator('.temporary-inbox__header').evaluate((element) => {
    const event = new MouseEvent('contextmenu', { bubbles: true, cancelable: true })
    element.dispatchEvent(event)
    return event.defaultPrevented
  })
  expect(prevented).toBe(true)
  await page.evaluate(() => {
    document.addEventListener('keydown', (event) => {
      if ((event.ctrlKey || event.metaKey) && event.key === 'f') document.documentElement.dataset.findPrevented = String(event.defaultPrevented)
    })
  })
  await body.press(process.platform==='darwin'?'Meta+f':'Control+f')
  await expect(page.locator('html')).toHaveAttribute('data-find-prevented', 'true')
  await page.getByRole('searchbox', { name: '搜索资料库' }).press('Escape')
  await body.click({ button: 'right' })
  await expect(page.getByRole('menu', { name: 'Markdown 快捷插入' })).toBeVisible()
})

test('sets toolbar headings and renders a legible collapsed format control', async ({ page }, testInfo) => {
  await page.goto('/e2e/rich-heading-fixture.html')
  const heading = page.locator('h4[data-rich-heading]')
  await heading.click()
  const style = page.getByRole('button', { name: '段落样式' })
  await expect(style).toHaveText('H')
  await style.click()
  const option = page.getByRole('menuitemradio', { name: '标题 2' })
  const normal = await option.evaluate((element) => ({ color: getComputedStyle(element).color, background: getComputedStyle(element).backgroundColor }))
  await option.hover()
  expect(await option.evaluate((element) => getComputedStyle(element).backgroundColor)).not.toEqual(normal.background)
  await page.screenshot({ path: testInfo.outputPath('heading-menu.png') })
  await option.click()
  await expect(page.locator('h2[data-rich-heading]')).toHaveText('## Self-Attention')
  await expect(page.getByRole('alert')).toHaveCount(0)
  await page.getByRole('button', { name: '收起格式工具栏' }).click()
  const expand = page.getByRole('button', { name: '展开格式工具栏' })
  await expect(expand).toBeVisible()
  await expect(expand).toHaveText('')
  await expect(page.getByRole('button', { name: '高亮', exact: true })).not.toBeVisible()
  await expect.poll(async () => (await page.getByRole('toolbar', { name: '文档格式' }).boundingBox())!.height).toBeLessThanOrEqual(1)
  await page.screenshot({ path: testInfo.outputPath('collapsed-toolbar.png') })
  await expand.click()
  await expect(style).toBeVisible()
})


test('applies font size on Enter only to the selected text and reports the caret size', async ({ page }) => {
  await page.goto('/e2e/rich-heading-fixture.html')
  const paragraph = page.getByRole('textbox', { name: '文档正文' }).locator('p').first()
  await paragraph.click()
  await paragraph.evaluate((element) => {
    const text = element.firstChild!
    const range = document.createRange()
    range.setStart(text, 0)
    range.setEnd(text, 2)
    const selection = window.getSelection()!
    selection.removeAllRanges()
    selection.addRange(range)
    element.dispatchEvent(new Event('mouseup', { bubbles: true }))
  })
  const input = page.getByRole('textbox', { name: '字号', exact: true })
  await input.fill('18')
  expect(await input.evaluate(element => getComputedStyle(element).boxShadow)).toBe('none')
  await expect(paragraph.locator('span[style*="font-size"]')).toHaveCount(0)
  await input.press('Enter')
  await expect(paragraph.locator('span[style*="font-size"]')).toHaveText('上方')
  await expect(input).toHaveValue('18')
  await page.getByRole('textbox', { name: '文档正文' }).locator('p').last().click()
  await expect(input).toHaveValue('11')
})

test('stars notes in the collapsed library and puts app actions in the titlebar', async ({ page }, testInfo) => {
  await page.goto('/')
  await expect(page.locator('.window-titlebar__brand')).toHaveText('微屿')
  await expect(page.locator('.window-titlebar').getByRole('button', { name: '打开设置', exact: true })).toBeVisible()
  const search = page.getByRole('searchbox', { name: '搜索笔记' })
  await expect(page.getByTestId('folder-pane').getByRole('searchbox', { name: '搜索笔记' })).toBeVisible()
  expect(await search.locator('..').evaluate(element => getComputedStyle(element).borderTopWidth)).toBe('1px')
  await page.getByRole('treeitem', { name: '项目', exact: true }).click()
  const note = page.getByRole('button', { name: '用户认证', exact: true })
  await note.click({ button: 'right' })
  await page.getByRole('menuitem', { name: '添加星标', exact: true }).click()
  await page.getByRole('button', { name: '折叠资料库' }).click()
  const rail = page.getByRole('navigation', { name: '折叠的资料库' })
  await expect(rail.locator('.library-rail__separator')).toHaveCount(1)
  await expect(rail.getByRole('button', { name: '用户认证', exact: true })).toBeVisible()
  const expand = (await rail.getByRole('button', { name: '展开资料库' }).boundingBox())!
  const inbox = (await rail.getByRole('button', { name: '临时便笺' }).boundingBox())!
  expect(expand.y).toBeLessThan(inbox.y)
  await rail.getByRole('button', { name: '用户认证', exact: true }).click()
  await expect(page.getByRole('heading', { name: '用户认证', exact: true })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('collapsed-library.png') })
  await rail.getByRole('button', { name: '展开资料库' }).click()
  await expect(search).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('single-titlebar.png') })
})


test('opens central folder and note search with Ctrl+F and resizes related notes above the footer', async ({page},testInfo) => {
  await page.goto('/')
  await page.keyboard.press(process.platform==='darwin'?'Meta+f':'Control+f')
  const search=page.getByRole('searchbox',{name:'搜索资料库'})
  await expect(search).toBeFocused()
  expect(await search.evaluate(element => getComputedStyle(element).boxShadow)).toBe('none')
  await search.fill('项目')
  await page.getByRole('option',{name:'文件夹 项目',exact:true}).click()
  await expect(search).toHaveCount(0)
  await page.getByRole('button',{name:'用户认证',exact:true}).click()
  const footer=page.getByLabel('笔记状态栏')
  await expect(footer).toContainText('字')
  await expect(footer.getByRole('status',{name:'保存状态'})).toBeVisible()
  await expect(page.locator('.window-titlebar').getByLabel('保存状态')).toHaveCount(0)
  await page.getByRole('button',{name:'关联笔记',exact:true}).click()
  const divider=page.getByRole('separator',{name:'调整关联笔记高度'})
  const before=Number(await divider.getAttribute('aria-valuenow'))
  const box=(await divider.boundingBox())!
  await page.mouse.move(box.x+box.width/2,box.y+4);await page.mouse.down();await page.mouse.move(box.x+box.width/2,box.y-56);await page.mouse.up()
  await expect.poll(async()=>Number(await divider.getAttribute('aria-valuenow'))).toBeGreaterThan(before+40)
  await page.screenshot({path:testInfo.outputPath('status-search.png')})
  await page.keyboard.press(process.platform==='darwin'?'Meta+f':'Control+f');await search.fill('认证')
  await expect(page.getByRole('option',{name:/用户认证/})).toBeVisible()
  await page.screenshot({path:testInfo.outputPath('search-results.png')})
})
